### ISSUE TITLE
Maximum mana input

### ISSUE THREAD

**Issue by jxu** [Lookas123/CCGrimoireCalculator#2]
The maximum mana depends only on wizard tower lvl and number of towers, so why isn't that calculated value (3rd line) used for the maximum mana box?
(Also I would call it full mana since "lowest maximum" is a little confusing here.)

**Comment by Lookas123** [comment]
The calculated value is not used on purpose: it's easy to input yourself, and would make it a bit annoying since currently there is no need to fill those boxes (except level for multicast)
I don't think full mana really represents what lowest maximum is supposed to; being the amount of maximum magic you'd have with one wizard tower.
